# Gradle and Android build properties
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8 --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX and automatic SDK download
android.useAndroidX=true
android.nonTransitiveRClass=true
android.builder.sdkDownload=true

# Kotlin & KSP
kotlin.daemon.jvmargs=-Xmx1536m
ksp.incremental=true
