# Gradle and Android build properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX and SDK download
android.useAndroidX=true
android.nonTransitiveRClass=true
android.builder.sdkDownload=true

# Kotlin
kotlin.daemon.jvmargs=-Xmx1024m
kapt.incremental.apt=true
